# https://taskfile.dev

version: "3"

vars:
  BINARY_NAME: birda

# Cross-compilation notes:
# - Linux ARM64: requires `gcc-aarch64-linux-gnu` package
# - macOS targets: requires macOS SDK (osxcross) or build on macOS
# - Windows GNU: requires `mingw-w64` package
# - ONNX Runtime: downloads platform-specific binaries automatically

tasks:
  default:
    desc: Run all checks (fmt, clippy, test)
    cmds:
      - task: check

  check:
    desc: Run all quality checks
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --check

  clippy:
    desc: Run clippy linter with strict warnings
    cmds:
      - cargo clippy -- -D warnings

  clippy:fix:
    desc: Run clippy and apply automatic fixes
    cmds:
      - cargo clippy --fix --allow-dirty --allow-staged

  test:
    desc: Run all tests
    cmds:
      - cargo test

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - cargo test -- --nocapture

  build:
    desc: Build for current platform (debug)
    cmds:
      - cargo build

  build:release:
    desc: Build for current platform (release)
    cmds:
      - cargo build --release

  # Native builds (recommended - no cross-compilation complexity)
  build:native:
    desc: Build release for current platform only
    cmds:
      - cargo build --release

  # Cross-compilation targets
  # These require appropriate toolchains installed

  build:linux-x64:
    desc: Build for Linux x86_64
    vars:
      TARGET: x86_64-unknown-linux-gnu
    cmds:
      - rustup target add {{.TARGET}} 2>/dev/null || true
      - cargo build --release --target {{.TARGET}}

  build:linux-arm64:
    desc: Build for Linux ARM64 (requires gcc-aarch64-linux-gnu)
    vars:
      TARGET: aarch64-unknown-linux-gnu
    env:
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    cmds:
      - rustup target add {{.TARGET}} 2>/dev/null || true
      - cargo build --release --target {{.TARGET}}

  build:macos-x64:
    desc: Build for macOS x86_64 (requires osxcross or native macOS)
    vars:
      TARGET: x86_64-apple-darwin
    cmds:
      - rustup target add {{.TARGET}} 2>/dev/null || true
      - cargo build --release --target {{.TARGET}}

  build:macos-arm64:
    desc: Build for macOS ARM64 (requires osxcross or native macOS)
    vars:
      TARGET: aarch64-apple-darwin
    cmds:
      - rustup target add {{.TARGET}} 2>/dev/null || true
      - cargo build --release --target {{.TARGET}}

  build:windows-x64:
    desc: Build for Windows x86_64 (requires mingw-w64)
    vars:
      TARGET: x86_64-pc-windows-gnu
    env:
      CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32-gcc
    cmds:
      - rustup target add {{.TARGET}} 2>/dev/null || true
      - cargo build --release --target {{.TARGET}}

  # Build all that work on current platform
  build:all-native:
    desc: Build for all Linux targets (from Linux host)
    cmds:
      - task: build:linux-x64

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  doc:
    desc: Generate documentation
    cmds:
      - cargo doc --no-deps

  doc:open:
    desc: Generate and open documentation
    cmds:
      - cargo doc --no-deps --open

  run:
    desc: Run birda with arguments
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  install:
    desc: Install birda to ~/.cargo/bin
    cmds:
      - cargo install --path .

  # CI-specific tasks
  ci:
    desc: Run full CI pipeline
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test
      - task: build:release
      - task: doc

  ci:lint:
    desc: Run linting checks for CI
    cmds:
      - task: fmt:check
      - task: clippy

  ci:test:
    desc: Run tests for CI
    cmds:
      - cargo test --no-fail-fast

  # Development helpers
  watch:
    desc: Watch for changes and run checks
    cmds:
      - cargo watch -c -x "fmt" -x "clippy" -x "test"

  pre-commit:
    desc: Run before committing (alias for check)
    cmds:
      - task: check

  # Cross-compilation setup helpers
  setup:cross-linux-arm64:
    desc: Install Linux ARM64 cross-compiler (Debian/Ubuntu)
    cmds:
      - sudo apt-get install -y gcc-aarch64-linux-gnu

  setup:cross-windows:
    desc: Install Windows cross-compiler (Debian/Ubuntu)
    cmds:
      - sudo apt-get install -y mingw-w64
